### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by polentino** [polentino/redacted#10]
Once this PR(*) gets approved and merged, add `sbt-sonatype` sbt plugin and configure properly.

(*) https://github.com/xerial/sbt-sonatype/pull/474

**Comment by Andrapyre** [comment]
Note: most projects use sbt-ci-release (link below), which incorporates the sbt-sonatype plugin, alongside several others. Depending on how urgent it is to release this, it may be better to wait until sbt-ci-release has been updated with the latest version of sbt-sonatype.

https://github.com/sbt/sbt-ci-release

**Comment by polentino** [comment]
Hi @Andrapyre , thanks for your comment and the advice, I'll keep that sbt plugin in mind 🙌
The project started as a personal "itch to scratch" combined with the idea to learn how scala 3 compiler plugin works, then I decided to go for the extra mile(s) and polish it properly, since I reckon it might be useful for somebody else out there as well.
For now the artifacts are published in GitHub and seem to be working fine. Therefore, no rush, nor urgency at all :)
